from __future__ import annotations

from app.strategy_candidate_filtered import FILTERED_CANDIDATE_STRATEGIES
from app.strategy_candidate_full_universe import FULL_UNIVERSE_CANDIDATE_STRATEGIES
from app.strategy_candidate_universe_variants import UNIVERSE_VARIANT_CANDIDATE_STRATEGIES


BASELINE_CANDIDATE_STRATEGIES = [
    *FULL_UNIVERSE_CANDIDATE_STRATEGIES,
    *FILTERED_CANDIDATE_STRATEGIES,
    *UNIVERSE_VARIANT_CANDIDATE_STRATEGIES,
]


__all__ = [
    "BASELINE_CANDIDATE_STRATEGIES",
    "FILTERED_CANDIDATE_STRATEGIES",
    "FULL_UNIVERSE_CANDIDATE_STRATEGIES",
    "UNIVERSE_VARIANT_CANDIDATE_STRATEGIES",
]
