from __future__ import annotations

from app.strategy_catalog import (
    CANONICAL_CANDIDATE_DEFINITIONS,
    REFERENCE_EQUAL_WEIGHT_WITH_CASH,
)
from app.strategy_presets import *


__all__ = [
    "CANONICAL_CANDIDATE_DEFINITIONS",
    "DEFAULT_INVESTMENT_UNIVERSE",
    "DEFAULT_RISK_CONTROLS",
    "DUAL_MOMENTUM_TOP3",
    "EQUAL_WEIGHT",
    "ETF_ONLY_INVESTMENT_UNIVERSE",
    "FULL_UNIVERSE",
    "FULL_UNIVERSE_MOMENTUM_LOW_VOL_TILT_LIGHT_TOP",
    "FULL_UNIVERSE_MOMENTUM_LOW_VOL_TILT_WEAK_TOP",
    "FULL_UNIVERSE_MOMENTUM_MACRO_TILT_LIGHT_TOP",
    "FULL_UNIVERSE_MOMENTUM_TILT",
    "FULL_UNIVERSE_MOMENTUM_TILT_STRONG",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_SOFTMAX",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_10M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_11M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_15M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_2M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_3M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_6M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_8M",
    "FULL_UNIVERSE_MOMENTUM_TILT_WEAK_TOP_9M",
    "HIERARCHICAL_RISK_PARITY",
    "MEAN_RISK_UTILITY",
    "MEAN_RISK_UTILITY_CONSERVATIVE",
    "MINIMUM_VARIANCE",
    "MOMENTUM_TOP3",
    "POSITIVE_MOMENTUM_HIGH_VOLUME_UNIVERSE",
    "POSITIVE_MOMENTUM_LOW_VOL_UNIVERSE",
    "REFERENCE_EQUAL_WEIGHT_WITH_CASH",
    "RISK_BUDGETING",
    "TRAILING_MOMENTUM_LOW_VOL_UNIVERSE",
]
