from __future__ import annotations

from app.strategy_candidate_baselines import BASELINE_CANDIDATE_STRATEGIES
from app.strategy_candidate_predictors import PREDICTOR_CANDIDATE_STRATEGIES
from app.strategy_candidate_timeframes import TIMEFRAME_VARIANT_CANDIDATE_STRATEGIES
from app.strategy_references import REFERENCE_EQUAL_WEIGHT_WITH_CASH


CANONICAL_CANDIDATE_STRATEGIES = [
    *BASELINE_CANDIDATE_STRATEGIES,
    *TIMEFRAME_VARIANT_CANDIDATE_STRATEGIES,
    *PREDICTOR_CANDIDATE_STRATEGIES,
]


__all__ = [
    "BASELINE_CANDIDATE_STRATEGIES",
    "CANONICAL_CANDIDATE_STRATEGIES",
    "PREDICTOR_CANDIDATE_STRATEGIES",
    "REFERENCE_EQUAL_WEIGHT_WITH_CASH",
    "TIMEFRAME_VARIANT_CANDIDATE_STRATEGIES",
]
